### ISSUE TITLE
[Feature Request] Bigger server banner size

### ISSUE THREAD

**Issue by xBiei** [userXinos/image-tools#15]
**Describe the feature request**
Get a bigger server banner image size for better quality.

**Expected behavior**
Getting a better quality image for a better life.

This probably needs a special function because from what I've seen here, 
this plugin gets the image source from the element itself and the default banner size is 512.

It's _not_ necessary feature but it would give a good experience.

**Comment by xBiei** [comment]
yeah ik but when directly saving or viewing the image from discord itself.
as I said above "It's _not_ necessary feature but it would give a good experience."

**Comment by userXinos** [comment]
of course it's not hard to implement

**Comment by xBiei** [comment]
> of course it's not hard to implement
that would be a good addition to this beautiful plugin,
thx.
