### ISSUE TITLE
Suggestion: add more info about images

### ISSUE THREAD

**Issue by SomeAspy** [userXinos/image-tools#2]
Lighty's version of this plugin for BD has a feature that shows details like image resolution, size, and name.
![image](https://user-images.githubusercontent.com/33640860/105542043-b717c380-5cc6-11eb-8a42-761bda869a96.png)

**Comment by userXinos** [comment]
yeah, basic information about the image in the plans

**Comment by Ayfri** [comment]
They should be copyable, so you can copy the link in the corner (and the image name/dimensions) :)

**Comment by userXinos** [comment]
ok, I think the basic info of the image can be considered complete, do not hesitate to open this issue if you have new ideas, well, or create a new issue
