### ISSUE TITLE
Lens disappearing when the pointer isn't on the image

### ISSUE THREAD

**Issue by Aokiare** [userXinos/image-tools#5]
here's an [example](https://femboy.thigh.pics/e5Bb064.webm)

**Comment by userXinos** [comment]
Let's admit. What would you like to see outside the image ?

Feature - https://github.com/userXinos/image-tools/blob/main/components/ImageWrapper.jsx#L43-L44

**Comment by Aokiare** [comment]
[this](https://femboy.thigh.pics/adB16E4.webm) is just more convenient no? it's fine if it was intentional ig

**Comment by jdadonut** [comment]
could be made into a setting
