### ISSUE TITLE
Make zoom more smooth and expandable.

### ISSUE THREAD

**Issue by Ayfri** [userXinos/image-tools#7]
In SaveToRedux, the BetterDiscord version of this plugin, it allows zooming from x1 through x1.2, x1.8, etc. up to about x40, this plugin only allows integers for zoom and only up to x20!

You should add precision up to 0.1 and zoom up to x40 (maybe more, on big images). _And maybe a slider to set the zoom speed?_

**Comment by userXinos** [comment]
With the current max zoom, I can already easily look at the pixels, why more?  And increasing the step for scrolling sounds interesting
